// Code generated by protoc-gen-go. DO NOT EDIT.
// source: study.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	study.proto

It has these top-level messages:
	Study
	StudyRequest
	StudyResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Study struct {
	Sid       int32  `protobuf:"varint,1,opt,name=sid" json:"sid,omitempty"`
	Age       int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Telephone string `protobuf:"bytes,4,opt,name=telephone" json:"telephone,omitempty"`
	Address   string `protobuf:"bytes,5,opt,name=address" json:"address,omitempty"`
}

func (m *Study) Reset()                    { *m = Study{} }
func (m *Study) String() string            { return proto1.CompactTextString(m) }
func (*Study) ProtoMessage()               {}
func (*Study) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Study) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *Study) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Study) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Study) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *Study) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type StudyRequest struct {
	Sid         int32  `protobuf:"varint,1,opt,name=sid" json:"sid,omitempty"`
	Information string `protobuf:"bytes,2,opt,name=information" json:"information,omitempty"`
}

func (m *StudyRequest) Reset()                    { *m = StudyRequest{} }
func (m *StudyRequest) String() string            { return proto1.CompactTextString(m) }
func (*StudyRequest) ProtoMessage()               {}
func (*StudyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StudyRequest) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *StudyRequest) GetInformation() string {
	if m != nil {
		return m.Information
	}
	return ""
}

type StudyResponse struct {
	Sid         int32  `protobuf:"varint,1,opt,name=sid" json:"sid,omitempty"`
	Information string `protobuf:"bytes,2,opt,name=information" json:"information,omitempty"`
}

func (m *StudyResponse) Reset()                    { *m = StudyResponse{} }
func (m *StudyResponse) String() string            { return proto1.CompactTextString(m) }
func (*StudyResponse) ProtoMessage()               {}
func (*StudyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *StudyResponse) GetSid() int32 {
	if m != nil {
		return m.Sid
	}
	return 0
}

func (m *StudyResponse) GetInformation() string {
	if m != nil {
		return m.Information
	}
	return ""
}

func init() {
	proto1.RegisterType((*Study)(nil), "proto.Study")
	proto1.RegisterType((*StudyRequest)(nil), "proto.StudyRequest")
	proto1.RegisterType((*StudyResponse)(nil), "proto.StudyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SelfManage service

type SelfManageClient interface {
	StudyAdd(ctx context.Context, in *Study, opts ...grpc.CallOption) (*StudyResponse, error)
	GetHelloTest(ctx context.Context, opts ...grpc.CallOption) (SelfManage_GetHelloTestClient, error)
	GetNxinMethod(ctx context.Context, in *StudyRequest, opts ...grpc.CallOption) (SelfManage_GetNxinMethodClient, error)
	GetStudy(ctx context.Context, opts ...grpc.CallOption) (SelfManage_GetStudyClient, error)
}

type selfManageClient struct {
	cc *grpc.ClientConn
}

func NewSelfManageClient(cc *grpc.ClientConn) SelfManageClient {
	return &selfManageClient{cc}
}

func (c *selfManageClient) StudyAdd(ctx context.Context, in *Study, opts ...grpc.CallOption) (*StudyResponse, error) {
	out := new(StudyResponse)
	err := grpc.Invoke(ctx, "/proto.SelfManage/StudyAdd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *selfManageClient) GetHelloTest(ctx context.Context, opts ...grpc.CallOption) (SelfManage_GetHelloTestClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SelfManage_serviceDesc.Streams[0], c.cc, "/proto.SelfManage/GetHelloTest", opts...)
	if err != nil {
		return nil, err
	}
	x := &selfManageGetHelloTestClient{stream}
	return x, nil
}

type SelfManage_GetHelloTestClient interface {
	Send(*StudyRequest) error
	CloseAndRecv() (*StudyResponse, error)
	grpc.ClientStream
}

type selfManageGetHelloTestClient struct {
	grpc.ClientStream
}

func (x *selfManageGetHelloTestClient) Send(m *StudyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *selfManageGetHelloTestClient) CloseAndRecv() (*StudyResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StudyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *selfManageClient) GetNxinMethod(ctx context.Context, in *StudyRequest, opts ...grpc.CallOption) (SelfManage_GetNxinMethodClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SelfManage_serviceDesc.Streams[1], c.cc, "/proto.SelfManage/GetNxinMethod", opts...)
	if err != nil {
		return nil, err
	}
	x := &selfManageGetNxinMethodClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SelfManage_GetNxinMethodClient interface {
	Recv() (*StudyResponse, error)
	grpc.ClientStream
}

type selfManageGetNxinMethodClient struct {
	grpc.ClientStream
}

func (x *selfManageGetNxinMethodClient) Recv() (*StudyResponse, error) {
	m := new(StudyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *selfManageClient) GetStudy(ctx context.Context, opts ...grpc.CallOption) (SelfManage_GetStudyClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SelfManage_serviceDesc.Streams[2], c.cc, "/proto.SelfManage/GetStudy", opts...)
	if err != nil {
		return nil, err
	}
	x := &selfManageGetStudyClient{stream}
	return x, nil
}

type SelfManage_GetStudyClient interface {
	Send(*StudyRequest) error
	Recv() (*StudyResponse, error)
	grpc.ClientStream
}

type selfManageGetStudyClient struct {
	grpc.ClientStream
}

func (x *selfManageGetStudyClient) Send(m *StudyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *selfManageGetStudyClient) Recv() (*StudyResponse, error) {
	m := new(StudyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SelfManage service

type SelfManageServer interface {
	StudyAdd(context.Context, *Study) (*StudyResponse, error)
	GetHelloTest(SelfManage_GetHelloTestServer) error
	GetNxinMethod(*StudyRequest, SelfManage_GetNxinMethodServer) error
	GetStudy(SelfManage_GetStudyServer) error
}

func RegisterSelfManageServer(s *grpc.Server, srv SelfManageServer) {
	s.RegisterService(&_SelfManage_serviceDesc, srv)
}

func _SelfManage_StudyAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Study)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SelfManageServer).StudyAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SelfManage/StudyAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SelfManageServer).StudyAdd(ctx, req.(*Study))
	}
	return interceptor(ctx, in, info, handler)
}

func _SelfManage_GetHelloTest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SelfManageServer).GetHelloTest(&selfManageGetHelloTestServer{stream})
}

type SelfManage_GetHelloTestServer interface {
	SendAndClose(*StudyResponse) error
	Recv() (*StudyRequest, error)
	grpc.ServerStream
}

type selfManageGetHelloTestServer struct {
	grpc.ServerStream
}

func (x *selfManageGetHelloTestServer) SendAndClose(m *StudyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *selfManageGetHelloTestServer) Recv() (*StudyRequest, error) {
	m := new(StudyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SelfManage_GetNxinMethod_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StudyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SelfManageServer).GetNxinMethod(m, &selfManageGetNxinMethodServer{stream})
}

type SelfManage_GetNxinMethodServer interface {
	Send(*StudyResponse) error
	grpc.ServerStream
}

type selfManageGetNxinMethodServer struct {
	grpc.ServerStream
}

func (x *selfManageGetNxinMethodServer) Send(m *StudyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SelfManage_GetStudy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SelfManageServer).GetStudy(&selfManageGetStudyServer{stream})
}

type SelfManage_GetStudyServer interface {
	Send(*StudyResponse) error
	Recv() (*StudyRequest, error)
	grpc.ServerStream
}

type selfManageGetStudyServer struct {
	grpc.ServerStream
}

func (x *selfManageGetStudyServer) Send(m *StudyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *selfManageGetStudyServer) Recv() (*StudyRequest, error) {
	m := new(StudyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SelfManage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SelfManage",
	HandlerType: (*SelfManageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StudyAdd",
			Handler:    _SelfManage_StudyAdd_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHelloTest",
			Handler:       _SelfManage_GetHelloTest_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetNxinMethod",
			Handler:       _SelfManage_GetNxinMethod_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetStudy",
			Handler:       _SelfManage_GetStudy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "study.proto",
}

func init() { proto1.RegisterFile("study.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xff, 0xfe, 0xb7, 0x81, 0xe6, 0x9a, 0x4a, 0xe8, 0x60, 0xb0, 0x10, 0x43, 0x94, 0x29,
	0x53, 0x15, 0xc1, 0x88, 0x40, 0x02, 0x86, 0xb0, 0x94, 0x21, 0xe5, 0x0b, 0x18, 0xf9, 0xda, 0x46,
	0x4a, 0xed, 0x10, 0xbb, 0x02, 0xbe, 0x3a, 0x13, 0xf2, 0x85, 0x8a, 0x22, 0xc1, 0x50, 0xa6, 0xdc,
	0xfd, 0x2e, 0xf7, 0x9e, 0x9f, 0x0d, 0x63, 0xe7, 0x37, 0xfa, 0x6d, 0xda, 0x76, 0xd6, 0x5b, 0x8c,
	0xf8, 0x93, 0xbd, 0x40, 0x34, 0x0f, 0x14, 0x8f, 0x60, 0xe0, 0x6a, 0x2d, 0x45, 0x2a, 0xf2, 0xa8,
	0x0a, 0x65, 0x20, 0x6a, 0x49, 0xf2, 0x7f, 0x4f, 0xd4, 0x92, 0x10, 0x61, 0x68, 0xd4, 0x9a, 0xe4,
	0x20, 0x15, 0x79, 0x5c, 0x71, 0x8d, 0x67, 0x10, 0x7b, 0x6a, 0xa8, 0x5d, 0x59, 0x43, 0x72, 0xc8,
	0x83, 0x2f, 0x80, 0x12, 0x0e, 0x95, 0xd6, 0x1d, 0x39, 0x27, 0x23, 0x9e, 0x6d, 0xdb, 0xec, 0x16,
	0x12, 0x36, 0xae, 0xe8, 0x79, 0x43, 0xce, 0xff, 0xe0, 0x9f, 0xc2, 0xb8, 0x36, 0x0b, 0xdb, 0xad,
	0x95, 0xaf, 0xad, 0xe1, 0x73, 0xc4, 0xd5, 0x2e, 0xca, 0xee, 0x60, 0xf2, 0xa9, 0xe1, 0x5a, 0x6b,
	0x1c, 0xfd, 0x45, 0xe4, 0xfc, 0x5d, 0x00, 0xcc, 0xa9, 0x59, 0xcc, 0x94, 0x09, 0x19, 0x0b, 0x18,
	0xb1, 0xe6, 0x8d, 0xd6, 0x98, 0xf4, 0x77, 0x35, 0x65, 0x70, 0x7a, 0xb2, 0xdb, 0x6d, 0x2d, 0xb3,
	0x7f, 0x78, 0x05, 0x49, 0x49, 0xfe, 0x9e, 0x9a, 0xc6, 0x3e, 0x86, 0x24, 0xc7, 0xdf, 0xff, 0xe3,
	0x78, 0xbf, 0x2d, 0xe7, 0x02, 0xaf, 0x61, 0x52, 0x92, 0x7f, 0x78, 0xad, 0xcd, 0x8c, 0xfc, 0xca,
	0xea, 0xbd, 0xf6, 0x0b, 0x81, 0x97, 0x30, 0x2a, 0xc9, 0xf7, 0x8f, 0xb8, 0x9f, 0x75, 0x21, 0x9e,
	0x0e, 0x78, 0x74, 0xf1, 0x11, 0x00, 0x00, 0xff, 0xff, 0x3e, 0x0e, 0xad, 0xba, 0x1b, 0x02, 0x00,
	0x00,
}
